server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/hotel_booking}
    username: ${DB_USERNAME:booking}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect